name: Android Release
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-dir: ./App
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Create the Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        working-directory: ${{env.working-dir}}
        run: |
          # import keystore from secrets
          echo $KEYSTORE_BASE64 | base64 -d > android/app/keystore.jks
      - uses: DamianReeves/write-file-action@master
        with:
          path: ${{env.working-dir}}/android/key.properties
          contents: |
            storePassword=${{secrets.KEYSTORE_PASS}}
            keyPassword=${{secrets.KEYSTORE_PASS}}
            keyAlias=key0
            storeFile=keystore.jks
          write-mode: overwrite
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Disable analytics
        run: flutter --disable-analytics
        working-directory: ${{env.working-dir}}
      - name: Get dependencies
        run: flutter pub get
        working-directory: ${{env.working-dir}}
      - name: Build Bundle
        run: flutter build appbundle --release
        working-directory: ${{env.working-dir}}
      - name: Build APK
        run: flutter build apk --release
        working-directory: ${{env.working-dir}}
      - name: Upload Android Release (Appbundle)
        uses: actions/upload-artifact@v2
        with:
          name: Appbundle
          path: build/app/outputs/bundle/release/app-release.aab
          working-directory: ${{env.working-dir}}
      - name: Upload Android Release (APK)
        uses: actions/upload-artifact@v2
        with:
          name: APK
          path: build/app/outputs/apk/release/app-release.apk
          working-directory: ${{env.working-dir}}
