name: Android Release
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get dependencies
        run: flutter pub get
      - name: Build Bundle
        run: flutter build appbundle --release
      - name: Build APK
        run: flutter build apk --release
      - name: Upload Android Release (Appbundle)
        uses: actions/upload-artifact@v2
        with:
          name: Appbundle
          path: build/app/outputs/bundle/release/app-release.aab
      - name: Upload Android Release (APK)
        uses: actions/upload-artifact@v2
        with:
          name: APK
          path: build/app/outputs/apk/release/app-release.apk
