name: Linux Release
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-dir: ./App
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - run: sudo apt-get update -y
      - run:  sudo apt-get install -y ninja-build libgtk-3-dev
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Disable analytics
        run: flutter --disable-analytics
        working-directory: ${{env.working-dir}}
      - name: Get dependencies
        run: flutter pub get
        working-directory: ${{env.working-dir}}
      - name: Enable linux build
        run: flutter config --enable-linux-desktop
      - name: Build Linux Binary
        run: flutter build linux --release
        working-directory: ${{env.working-dir}}
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: ServerCtrl-Linux.zip
          directory: App/build/linux/x64/release/bundle
      - name: Upload Linux Release
        uses: actions/upload-artifact@v2
        with:
          name: Linux
          path: App/build/linux/x64/release/bundle/ServerCtrl-Linux.zip
